image: node:10

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm install --quiet
    - npm install -g wait-on --quiet
    - npm run build
  artifacts:
    paths:
      - dist/yami/

test:
  stage: test
  dependencies:
    - build
  cache:
    policy: pull
    paths:
      - node_modules/
  script:
    - npm run test
    - npm start & wait-on http://localhost:4200
    - npm run cy:run

deploy_prod:
  stage: deploy
  environment: 
    name: production
    url: $FIREBASE_URL
  only: 
   - master
  dependencies:
    - build
  cache:
    policy: pull
    paths:
      - node_modules/
  script:
    - npm install -g firebase-tools
    - npm run deploy
